// 42 x 21

pub const WIN11: [&'static str; 21] = [
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWW"
];