// 35 x 19
pub const LINES: usize = 23;

pub const WIN11: [&'static str; 19] = [
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW"
];

pub const WIN10: [&'static str; 19] = [
    "\x1b[1;34m                                 .,",
    "\x1b[1;34m                      ..,,:;+wwWWWW",
    "\x1b[1;34m        ....,+:;   wwWWWWWWWWWWWWWW",
    "\x1b[1;34m...,wwwWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34mWWWWWWWWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34m```*wwwWWWWWWWWW   WWWWWWWWWWWWWWWW",
    "\x1b[1;34m        ``'\\\\*::   wWWWWWWWWWWWWWWW",
    "\x1b[1;34m                      ````''**::wWW",
    "\x1b[1;34m                                 ``"
];